source 'https://rubygems.org'

group :development, :test do
  gem 'dotenv-rails', '~> 2.0.1', require: 'dotenv/rails-now'
end

gem 'rails', '~> 4.2.1'
gem 'turbolinks', '~> 2.5.3'
gem 'jquery-rails', '~> 4.0.3'
gem 'jquery-turbolinks', '~> 2.1.0'
#gem 'jbuilder'

gem 'font-awesome-rails', '~> 4.3.0'
gem 'bootstrap-sass', '~> 3.3.4'

gem 'pg', '~> 0.18.2'
gem 'redis-rails', '~> 4.0.0'

gem 'unicorn', '~> 4.9.0'
#gem 'puma', '~> 2.11.2'
gem 'sidekiq', '~> 3.3.4'
gem 'sinatra', '>= 1.4.5', require: false

gem 'whenever', '~> 0.9.4', require: false

gem 'sitemap_generator', '~> 5.0.5'
gem 'favicon_maker', '~> 1.3'
gem 'kaminari', '~> 0.16.3'

group :development do
  gem 'foreman', require: false
  gem 'spring', '~> 1.3.6'
  gem 'web-console', '~> 2.1.2'
  gem 'rack-mini-profiler', '~> 0.9.3'
  gem 'bullet', '~> 4.14.7'
  gem 'meta_request', '~> 0.3.0'
  gem 'railroady', '~> 1.3.0', require: false
end

group :assets do
  gem 'sass-rails', '~> 5.0.0'
  gem 'coffee-rails', '~> 4.1.0'
  gem 'uglifier', '~> 2.7.1'
end

group :doc do
  gem 'sdoc', '~> 0.4.0', require: false
end
