source 'https://rubygems.org'

gem 'rails', '~> 4.2.0.rc3'
gem 'turbolinks', '~> 2.5.3'
gem 'jquery-rails', '~> 4.0.1'
gem 'jquery-turbolinks', '~> 2.1.0'
#gem 'jbuilder'

gem 'font-awesome-rails', '~> 4.2.0'
gem 'bootstrap-sass', '~> 3.3.1'

gem 'pg', '~> 0.17.1'
gem 'redis-rails', '~> 4.0.0'

gem 'unicorn', '~> 4.8.3'
#gem 'puma', '~> 2.10.2'
gem 'sidekiq', '~> 3.3.0'
gem 'sinatra', '>= 1.4.5', require: false

gem 'whenever', '~> 0.9.4', require: false

gem 'sitemap_generator', '~> 5.0.5'
gem 'favicon_maker', '~> 1.3'
gem 'kaminari', '~> 0.16.1'

group :development do
  gem 'foreman', require: false
  gem 'spring', '~> 1.2.0'
  gem 'rack-mini-profiler', '~> 0.9.1'
  gem 'bullet', '~> 4.14.0'
  gem 'meta_request', '~> 0.3.0'
  gem 'railroady', '~> 1.1.1', require: false
end

group :development, :test do
  gem 'dotenv-rails', '~> 1.0.2'
end

group :assets do
  gem 'sass-rails', '~> 5.0.0'
  gem 'coffee-rails', '~> 4.1.0'
  gem 'uglifier', '~> 2.6.0'
end

group :doc do
  gem 'sdoc', '~> 0.4.0', require: false
end
